#security:
#  oauth2:
#    client:
#       clientId: 2135c14dfe0f69d7e179
#       clientSecret: 96483d3ab53b82f95e364c962e37ebc94fadfd1c
#       accessTokenUri: https://github.com/login/oauth/access_token
#       userAuthorizationUri: https://github.com/login/oauth/authorize
#       clientAuthenticationScheme: form
#    resource:
#      user-info-uri: https://api.github.com/user
#      prefer-token-info: false

spring:
  security:
    oauth2:
      client:
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/616d34d1-077e-403c-ae26-70bad548161b/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/616d34d1-077e-403c-ae26-70bad548161b/oauth2/v2.0/token
            issuer-uri: https://login.microsoftonline.com/616d34d1-077e-403c-ae26-70bad548161b/v2.0
            jwk-set-uri: https://login.microsoftonline.com/616d34d1-077e-403c-ae26-70bad548161b/discovery/v2.0/keys
            user-name-attribute: name
        registration:
          azure-dev:
            provider: azure
            client-id: e8768b29-112a-435e-93dd-9c805a2158d7
            client-secret:
            client-authentication-method: private_key_jwt
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/azure-dev
            scope:
              - openid
              - email
              - profile
              - https://graph.microsoft.com/User.Read
baeldung:
  jwt:
    authorization:
      group-to-authorities:
        "ceef656a-fca9-49b6-821b-f7543b7065cb": BAELDUNG_RW
        "eaaecb69-ccbc-4143-b111-7dd1ce1d99f1": BAELDUNG_RO,BAELDUNG_ADMIN